#!/bin/bash

make clean
make test_age
./test_age
make test_genre
./test_genre
make test_library
./test_library
make test_media
./test_media
make test_patron
./test_patron
make test_publication
./test_publication

make test_view
./test_view > test_view_actual.txt
diff test_view_expected.txt test_view_actual.txt > /dev/null 2>&1
if [ $? -ne 0 ] ; then
   echo "Error in class View (from test_view.cpp)"
   echo "Expected"
   echo "========"
   cat test_view_expected.txt
   echo
   echo "Actual"
   echo "======"
   cat test_view_actual.txt
   echo
   echo "fail"
fi

